title: </> Peter Krijgsman
logo: /assets/img/profile.jpg
description: Minimal is a theme for GitHub Pages.
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
show_downloads: false
