title: </> Peter Krijgsman
logo: /assets/img/profile.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
show_downloads: false