# Site
repository: Peterkrijgsman85/Peterkrijgsman85.github.io
favicon: images/favicon.png

# Content configuration version
version: 2

# Personal info
name: Peter Krijgsman
title: Projectmanager Cloud Communications and website builder with MkDocs
# email: peter.krijgsman@gmail.com
# website: https://pekri.nl

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  Peterkrijgsman85
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: krijgsmanpeter

# Additional icon links
additional_links:
- title: LanTel
  icon: fas fa-globe
  url: https://lantel.nl
- title: onlinebijbelverklaring.nl
  icon: fas fa-book-open
  url: https://onlinebijbelverklaring.nl

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi my name is Peter and I am a project manager at LanTel. As a project manager I am involved in implementing Cloud Communication solutions at our customers. In my own time i'm working on projects made with MkDocs.

  I am skilled in: <mark>Cloud Communications / UCaaS</mark> <mark>Projectmanagement</mark> <mark>MkDocs</mark>

content:
  - title: Personal Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Onlinebijbelverklaring.nl
        link: github.com/onlinebijbelverklaring
        # link_text: Project Website
        additional_links:
          - title:  onlinebijbelverklaring/onlinebijbelverklaring.github.io
            icon: fab fa-github
            url: github.com/onlinebijbelverklaring/onlinebijbelverklaring.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Complete online Bible commentary, powered by mkdocs
        description: | # this will include new lines to allow paragraphs
          I started this project after doing a few pilot projects for documentation webpages with MkDocs as a basis. That's how I got to know MkDocs. In the meantime, the website has grown into a large project.

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: LanTel
        link: lantel.nl
        link_text: lantel.nl
        sub_title: Projectmanagement
        caption: January 2009 - Present
        quote: >
          Started as an engineer, and now project manager
        description: | # this will include new lines to allow paragraphs
            The rapidly changing world of ICT is a domain where I feel at home. I am always busy with technology. With care, attention and creativity, I ensure good solutions, good service, and satisfied customers. I have been working at LanTel for over 16 years now. 
            
            We have been ensuring that organizations are optimally accessible for over 25 years. With our knowledge and personal approach, we are able to offer a high-quality and reliable business telephony solution for every challenge.
            
            We do this by communicating clearly to our relations in the things we do. We are passionate about our work and are flexible. This allows us to think along with our customers with a fresh perspective and offer the most suitable solution.
            
            As a project manager, I am responsible for the proper delivery of projects. In short, this involves: <mark>Maintaining contact with the client and internal organizational departments</mark>, <mark>Planning, initiating and coordinating activities</mark>, <mark>Supporting team members</mark>,<mark>Monitoring the progress of the implementation</mark>, <mark>Administrative processing of contracts that belong to the project</mark>


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed
