site_name: peterkrijgsman85.github.io
site_url: https://peterkrijgsman85.github.io/

theme:
  icon:
    repo: fontawesome/brands/github
    logo: material/github
  name: material
  features:
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - toc.follow
    - content.tabs.link
    - content.code.annotatioin
    - content.code.copy
    - header.autohide
  language: nl
  palette:
      # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Automatisch
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Lichte modus
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Donkere modus

plugins: []

extra:
  social:
    - icon: material/linkedin
      link: https://www.linkedin.com/in/krijgsmanpeter/
    - icon: material/github
      link: https://github.com/Peterkrijgsman85 


markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true

copyright: |
  &copy; 2024 <a href="https://peterkrijgsman85.github.io" target="_blank" rel="noopener">peterkrijgsman85.github.io<a>
